import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { Brain, Image, MessageSquare, Zap, Shield, Lock, Rocket, Infinity, Gift, User, Globe2, ArrowRight, Download, Trash2, Send, Menu, X } from 'lucide-react';
import './styles.css';

const dict={
 ru:{home:'Главная',chat:'AI Чат',image:'Генератор изображений',history:'История',pricing:'Тарифы',faq:'FAQ',login:'Войти',start:'Начать бесплатно',hero1:'Ваш AI-помощник',hero2:'для общения и творчества',heroText:'Общайтесь с ИИ, генерируйте изображения и воплощайте любые идеи в реальность',free:'5 бесплатных кредитов после регистрации',chatTitle:'AI Чат',chatDesc:'Задавайте любые вопросы и получайте умные ответы',imgTitle:'Генерация изображений',imgDesc:'Создавайте уникальные изображения по текстовому описанию',fastTitle:'Быстро и просто',fastDesc:'Современные AI-модели для максимального результата',users:'Пользователей',dialogs:'AI диалогов',created:'Создано изображений',uptime:'Доступность сервиса',safe:'Безопасно',safeD:'Ваши данные под защитой',conf:'Конфиденциально',confD:'Мы не передаем данные третьим лицам',quick:'Быстро',quickD:'Мгновенные ответы и генерация',unlim:'Без ограничений',unlimD:'Творите и общайтесь без границ',placeholder:'Напишите вопрос ИИ...',send:'Отправить',demo:'Это демо-ответ. После подключения API здесь будет настоящий ответ ИИ.',prompt:'Опишите изображение...',generate:'Создать изображение',credits:'Кредиты',profile:'Профиль',email:'Email',password:'Пароль',register:'Регистрация',logout:'Выйти',name:'Имя',buy:'Купить кредиты',empty:'Пока пусто',tariffs:'Тарифы',soon:'Оплата будет подключена позже'},
 en:{home:'Home',chat:'AI Chat',image:'Image Generator',history:'History',pricing:'Pricing',faq:'FAQ',login:'Login',start:'Start free',hero1:'Your AI assistant',hero2:'for chat and creativity',heroText:'Chat with AI, generate images and turn any idea into reality',free:'5 free credits after registration',chatTitle:'AI Chat',chatDesc:'Ask anything and get smart answers',imgTitle:'Image generation',imgDesc:'Create unique images from text prompts',fastTitle:'Fast and simple',fastDesc:'Modern AI models for maximum results',users:'Users',dialogs:'AI dialogs',created:'Images created',uptime:'Service uptime',safe:'Secure',safeD:'Your data is protected',conf:'Private',confD:'We do not share your data',quick:'Fast',quickD:'Instant answers and generation',unlim:'Unlimited',unlimD:'Create and chat without limits',placeholder:'Ask AI something...',send:'Send',demo:'This is a demo answer. After API setup, real AI responses will appear here.',prompt:'Describe an image...',generate:'Generate image',credits:'Credits',profile:'Profile',email:'Email',password:'Password',register:'Register',logout:'Logout',name:'Name',buy:'Buy credits',empty:'Nothing here yet',tariffs:'Pricing',soon:'Payments will be connected later'}
};
function App(){const[lang,setLang]=useState('ru');const[page,setPage]=useState('home');const[mobile,setMobile]=useState(false);const[user,setUser]=useState(()=>JSON.parse(localStorage.getItem('np_user')||'null'));const[credits,setCredits]=useState(()=>Number(localStorage.getItem('np_credits')||5));const[history,setHistory]=useState(()=>JSON.parse(localStorage.getItem('np_history')||'[]'));const t=dict[lang];const nav=['home','chat','image','history','pricing','faq'];function saveUser(u){setUser(u);localStorage.setItem('np_user',JSON.stringify(u));localStorage.setItem('np_credits',String(credits));}function addHistory(item){const h=[item,...history];setHistory(h);localStorage.setItem('np_history',JSON.stringify(h));}function dec(){const c=Math.max(0,credits-1);setCredits(c);localStorage.setItem('np_credits',String(c));}
return <><header><div className="brand" onClick={()=>setPage('home')}><Brain/><b>NeuroPic <span>AI</span></b></div><nav className={mobile?'open':''}>{nav.map(n=><button key={n} onClick={()=>{setPage(n);setMobile(false)}} className={page===n?'active':''}>{t[n]}</button>)}</nav><div className="actions"><button className="pill" onClick={()=>setLang(lang==='ru'?'en':'ru')}><Globe2 size={16}/>{lang.toUpperCase()}</button>{user?<button className="outline" onClick={()=>setPage('profile')}>{user.name||'User'} • {credits}</button>:<button className="outline" onClick={()=>setPage('login')}>{t.login}</button>}<button className="cta" onClick={()=>setPage(user?'image':'login')}>{t.start}</button><button className="burger" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header><main>{page==='home'&&<Home t={t} setPage={setPage}/>} {page==='login'&&<Auth t={t} saveUser={saveUser} setPage={setPage}/>} {page==='chat'&&<Chat t={t} user={user} setPage={setPage}/>} {page==='image'&&<ImageGen t={t} user={user} setPage={setPage} credits={credits} dec={dec} addHistory={addHistory}/>} {page==='history'&&<History t={t} history={history}/>} {page==='pricing'&&<Pricing t={t}/>} {page==='profile'&&<Profile t={t} user={user} credits={credits} setUser={setUser} setPage={setPage}/>} {page==='faq'&&<FAQ lang={lang}/>}</main><footer>© 2026 NeuroPic AI • RU / EN • Demo MVP</footer></>}
function Home({t,setPage}){return <section className="hero"><div className="heroText"><h1>{t.hero1}<br/><span>{t.hero2}</span></h1><p>{t.heroText}</p><div className="heroBtns"><button className="cta big" onClick={()=>setPage('login')}>{t.start}<ArrowRight/></button><button className="outline big" onClick={()=>setPage('login')}>{t.login}<User/></button></div><div className="gift"><Gift/>{t.free}</div></div><div className="orb"><div className="brain"><Brain/><b>AI</b></div></div><div className="cards"><Card icon={<MessageSquare/>} title={t.chatTitle} desc={t.chatDesc}/><Card icon={<Image/>} title={t.imgTitle} desc={t.imgDesc}/><Card icon={<Zap/>} title={t.fastTitle} desc={t.fastDesc}/></div><div className="stats"><Stat n="10K+" l={t.users}/><Stat n="50K+" l={t.dialogs}/><Stat n="30K+" l={t.created}/><Stat n="99.9%" l={t.uptime}/></div><div className="mini"><Card icon={<Shield/>} title={t.safe} desc={t.safeD}/><Card icon={<Lock/>} title={t.conf} desc={t.confD}/><Card icon={<Rocket/>} title={t.quick} desc={t.quickD}/><Card icon={<Infinity/>} title={t.unlim} desc={t.unlimD}/></div></section>}
function Card(p){return <div className="card"><div className="ico">{p.icon}</div><h3>{p.title}</h3><p>{p.desc}</p></div>}
function Stat({n,l}){return <div><b>{n}</b><span>{l}</span></div>}
function Auth({t,saveUser,setPage}){const[name,setName]=useState('');const[email,setEmail]=useState('');return <section className="panel auth"><h2>{t.register}</h2><input placeholder={t.name} value={name} onChange={e=>setName(e.target.value)}/><input placeholder={t.email} value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder={t.password} type="password"/><button className="cta big" onClick={()=>{saveUser({name:name||'User',email:email||'demo@neuropic.ai',date:new Date().toLocaleDateString()});setPage('image')}}>{t.start}</button><p>{t.free}</p></section>}
function Chat({t,user,setPage}){const[msg,setMsg]=useState('');const[list,setList]=useState([]);if(!user)return <NeedLogin t={t} setPage={setPage}/>;return <section className="panel chat"><h2>{t.chatTitle}</h2><div className="chatbox">{list.map((m,i)=><div key={i} className={m.role}>{m.text}</div>)}</div><div className="inputrow"><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder={t.placeholder}/><button className="cta" onClick={()=>{if(!msg)return;setList([...list,{role:'me',text:msg},{role:'ai',text:t.demo}]);setMsg('')}}><Send size={18}/>{t.send}</button></div></section>}
function ImageGen({t,user,setPage,credits,dec,addHistory}){const[p,setP]=useState('');const[img,setImg]=useState('');if(!user)return <NeedLogin t={t} setPage={setPage}/>;return <section className="panel"><h2>{t.imgTitle}</h2><div className="credits">{t.credits}: <b>{credits}</b></div><textarea value={p} onChange={e=>setP(e.target.value)} placeholder={t.prompt}/><button className="cta big" disabled={!p||credits<1} onClick={()=>{dec();const svg=`data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1024' height='1024'><defs><radialGradient id='g'><stop stop-color='#55ff12'/><stop offset='1' stop-color='#020302'/></radialGradient></defs><rect width='100%' height='100%' fill='#020302'/><circle cx='512' cy='420' r='260' fill='url(#g)' opacity='.5'/><text x='512' y='490' text-anchor='middle' fill='#55ff12' font-size='64' font-family='Arial' font-weight='700'>NeuroPic AI</text><text x='512' y='575' text-anchor='middle' fill='white' font-size='30' font-family='Arial'>${p.slice(0,48)}</text></svg>`)}`;setImg(svg);addHistory({prompt:p,img:svg,date:new Date().toLocaleString()})}}>{t.generate}</button>{credits<1&&<p className="warn">{t.buy}</p>}{img&&<div className="result"><img src={img}/><a className="outline" download="neuropic-demo.svg" href={img}><Download/>Download</a></div>}</section>}
function History({t,history}){return <section className="panel"><h2>{t.history}</h2>{!history.length?<p>{t.empty}</p>:<div className="gallery">{history.map((h,i)=><div className="work" key={i}><img src={h.img}/><b>{h.prompt}</b><small>{h.date}</small></div>)}</div>}</section>}
function Pricing({t}){return <section className="panel"><h2>{t.tariffs}</h2><div className="prices"><Plan n="Free" p="0₽" d="5 credits"/><Plan n="Start" p="199₽" d="100 credits"/><Plan n="Pro" p="499₽" d="350 credits"/></div><p>{t.soon}</p></section>}
function Plan({n,p,d}){return <div className="price"><h3>{n}</h3><b>{p}</b><p>{d}</p><button className="cta">Выбрать</button></div>}
function Profile({t,user,credits,setUser,setPage}){if(!user)return <NeedLogin t={t} setPage={setPage}/>;return <section className="panel auth"><h2>{t.profile}</h2><p>{t.name}: <b>{user.name}</b></p><p>{t.email}: <b>{user.email}</b></p><p>{t.credits}: <b>{credits}</b></p><button className="outline" onClick={()=>{localStorage.clear();setUser(null);setPage('home')}}>{t.logout}</button></section>}
function FAQ({lang}){return <section className="panel"><h2>FAQ</h2><h3>{lang==='ru'?'Это уже подключено к настоящему ИИ?':'Is real AI connected?'}</h3><p>{lang==='ru'?'Нет, это первая демо-версия интерфейса. API подключается на следующем этапе.':'No, this is the first interface demo. API comes next.'}</p></section>}
function NeedLogin({t,setPage}){return <section className="panel auth"><h2>{t.login}</h2><p>{t.free}</p><button className="cta big" onClick={()=>setPage('login')}>{t.start}</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
